package com.aideclare.airline

import com.aideclare.entities.dsl.syntax.id
import com.aideclare.entities.dsl.typeclasses.EntityMetadata


case class Company(
                    @id(autogenerated = true) id: Long,
                    name: String
                  ) derives EntityMetadata