package com.aideclare.airline

import com.aideclare.entities.dsl.syntax.id
import com.aideclare.entities.dsl.syntax.fk
import com.aideclare.entities.dsl.syntax.password
import com.aideclare.entities.dsl.syntax.username
import com.aideclare.entities.dsl.typeclasses.EntityMetadata
import com.aideclare.entities.dsl.typeclasses.UserInfo


final case class CompanyAdmin(
    @id(autogenerated = true) id: Long,
    @fk[Company] companyId: Long,
    @username username: String,
    @password password: String
)derives EntityMetadata, UserInfo
