package com.aideclare.airline

import com.aideclare.entities.dsl.syntax.id

import com.aideclare.entities.dsl.syntax.username
import com.aideclare.entities.dsl.syntax.password
import com.aideclare.entities.dsl.typeclasses.{EntityMetadata, UserInfo}

case class Customer(
    @id(autogenerated = true) id: Long,
    @username username: String,
    @password password: String,
    name: String,
    surname: String,
    nif: String
) derives EntityMetadata, UserInfo
