package com.aideclare.airline

import com.aideclare.entities.dsl.syntax.{fk, id}
import com.aideclare.entities.dsl.typeclasses.EntityMetadata
import java.time.LocalDateTime

case class Flight(
                   @id(autogenerated = true) id: Long,
                   number: Long,
                   origin: String,
                   destination: String,
                   flightDate: LocalDateTime,
                   @fk[Company] companyId: Long
                 ) derives EntityMetadata
