package com.aideclare.airline

import com.aideclare.entities.dsl.syntax.id
import com.aideclare.entities.dsl.typeclasses.EntityMetadata
import com.aideclare.entities.dsl.syntax.fk

final case class Passenger(
    @id(autogenerated= true) id: Long,
    @fk[Customer] customerId: Long,
    @fk[Flight] flightId: Long,
    seatNumber: String
) derives EntityMetadata
