package com.aideclare.entities

import com.aideclare.entities.dsl.syntax.{id, password, username}
import com.aideclare.entities.dsl.typeclasses.{EntityMetadata, UserInfo}

case class Professor(@id(autogenerated = true) id: Int,
                     @username email: String,
                     name: String,
                     @password password: String,
                     surname: String
                  )derives EntityMetadata, UserInfo
